name: to_note
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  gap: ^3.0.1
  flutter_screenutil: ^5.9.3
  animate_do: ^3.3.4
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  equatable: ^2.0.5
  lottie: ^3.1.2
  pinput: ^5.0.0
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
