// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP2IgvSIGCP6yUMoWRFU0aGDDBODiy-Cg',
    appId: '1:784639952450:web:a9343c3c223f041df38fdb',
    messagingSenderId: '784639952450',
    projectId: 'todo-87180',
    authDomain: 'todo-87180.firebaseapp.com',
    storageBucket: 'todo-87180.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIH1Ztn8zLkkr0nFJeSlLiYwPWM-4580g',
    appId: '1:784639952450:android:a51fa494ef43d49af38fdb',
    messagingSenderId: '784639952450',
    projectId: 'todo-87180',
    storageBucket: 'todo-87180.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ4WDYOh0hZaaOzIc8RLESoAMSn1QFXiQ',
    appId: '1:784639952450:ios:1c6a6ec5347636f6f38fdb',
    messagingSenderId: '784639952450',
    projectId: 'todo-87180',
    storageBucket: 'todo-87180.appspot.com',
    iosBundleId: 'com.example.toNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJ4WDYOh0hZaaOzIc8RLESoAMSn1QFXiQ',
    appId: '1:784639952450:ios:1c6a6ec5347636f6f38fdb',
    messagingSenderId: '784639952450',
    projectId: 'todo-87180',
    storageBucket: 'todo-87180.appspot.com',
    iosBundleId: 'com.example.toNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP2IgvSIGCP6yUMoWRFU0aGDDBODiy-Cg',
    appId: '1:784639952450:web:33fa187e0c7d8689f38fdb',
    messagingSenderId: '784639952450',
    projectId: 'todo-87180',
    authDomain: 'todo-87180.firebaseapp.com',
    storageBucket: 'todo-87180.appspot.com',
  );
}
